config/routes.rb
Rails.application.routes.draw do
  resources :flights
  root "flights#index"
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: :departure_airport , class_name: 'Flight'
    has_many :arriving_flights, foreign_key: :arriving_airport , class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight
    has_many :passengers
    accepts_nested_attributes_for :passengers, :allow_destroy => :true
    
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport , foreign_key: :departure_airport_id, class_name:'Airport'
    belongs_to :arrival_airport , foreign_key: :arrival_airport_id, class_name:'Airport'
    has_many :bookings
    def self.dates
       
        pluck(:start_datetime).uniq.map{|datetime| [datetime.strftime('%d/%m/%Y %H:%M'),datetime.strftime('%Y-%m-%d %H:%M:00')]}
    end
    def self.search(flight_params) 
        if flight_params.empty?
            nil
        else 
        results = Flight.all
        results=results.where(['departure_airport_id = ?',flight_params[:departure_airport].to_i ])if flight_params[:departure_airport].present?
        results=results.where([ 'arrival_airport_id= ?',flight_params[:arrival_airport]])  if flight_params[:arrival_airport].present? 
        results=results.where([ 'start_datetime=?',flight_params[:start_datetime]]) if flight_params[:start_datetime].present?          
        return results
        end
    end    
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
    validates :name, presence: true
    validates :email,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def create
        @flight = Flight.find(booking_params[:flight_id])
    @booking = @flight.bookings.build booking_params
    
    if blank_params &&  @booking.save 
        redirect_to @booking
    else
      flash.now[:alert] = "Fill all passenger info"
      render 'new'
    end
    end
    def show
        @booking = Booking.find(params[:id])
        @flight = @booking.flight
    end        
    private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end
    def blank_params
      params[:booking][:passengers_attributes].each do |key,value|
        value.each do |k,v|
          return false if v.blank?
        end
      end
              

    end  
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    if params[:commit] == 'Search'
    
      @airports = Airport.pluck :airport_code, :id
      @start_datetime = Flight.order(:start_datetime).dates
      @results = Flight.search(flight_params)
      @num_passengers = flight_params[:num_passengers] 
      render 'index'
    elsif params[:commit] == "Book"
      @num_passengers = booking_params[:num_passengers]
      @flight = Flight.find(booking_params[:flight_id])
      @booking = @flight.bookings.build
      (@num_passengers.to_i).times {|index| @booking.passengers.build }
      render 'bookings/new'
     
    else
    @airports = Airport.pluck :airport_code , :id
    @start_datetime = Flight.dates
    end
  end
  private
   def flight_params
    params.require(:flight).permit(:departure_airport, :arrival_airport, :start_datetime, :num_passengers) 
   end 
   def booking_params
    params.require(:booking).permit(:num_passengers, :flight_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<article>
<h4>Departure Airport:</h4>
<p><%= @flight.departure_airport.airport_code%></p>
<h4>Arrival Airport:</h4>
<p><%= @flight.arrival_airport.airport_code%></p>
<h4>Taking off at:</h4>
<p><%= @flight.start_datetime.strftime("%d/%m/%Y %H:%M") %></p>
<h4>Duration:</h4>
<p><%= @flight.flight_duration %> hours</p>
<h3>Pass:<%= @num_passengers %></h3>
</article>
<%= form_with model: @booking, url: bookings_path,data:{turbo:false} do |f| %>
   
    
    <%= f.fields_for :passengers, @booking.passengers,data:{turbo:false} do |form| %>
        <div>
        
          <%= form.text_field :name, placeholder: 'What is passenger name?' %>
          <%= form.email_field :email, placeholder: 'example@email.com' %>
          </div>
          <% end %>
          
          
          
          <%= hidden_field_tag 'booking[flight_id]', @flight.id %>
          <%= f.submit 'Book' %>
          <%end%>
        

app/views/bookings/show.html.erb
<article>
<div >
  <p>Thank you for your booking</p>
</div>
<div >
  Your plane will fly from <b><%= @flight.departure_airport.airport_code %></b>
  to <b><%= @flight.arrival_airport.airport_code %></b>
  at <b><%= @flight.start_datetime.strftime('%d-%m-%Y %H:%M') %></b>. <br>
  The plane will take <b><%= @flight.flight_duration %></b> hour(s). <br><br>

  Passenger(s): <br>
  <% @booking.passengers.each do |b| %>
    <li>Name: <b><%= b.name %></b>, email: <b><%= b.email %></b></li>
  <% end %> <br>
  See you soon.
</div>
</article>

app/views/flights/_results.html.erb
<% if @results.present? %>
<table  >
<%= form_with scope: :booking, url: flights_path, method: :get, local: true,data:{turbo:false} do |f| %>
    <%= f.hidden_field  :num_passengers ,value:@num_passengers %>
  <tr>
    <th></th>
    <th>From</th>
    <th>To</th>
    <th>Date</th>
    <th>Tickets</th>
  </tr>
  <% @results.each do |flight| %>

    <tr>
    <td><%= @results[0] == flight ? radio_button_tag('booking[flight_id]', flight.id, selected: true) : radio_button_tag('booking[flight_id]', flight.id) %></td>
      <td><%= flight.departure_airport.airport_code %></td>
      <td><%= flight.arrival_airport.airport_code %></td>
      <td><%= flight.start_datetime.strftime('%d/%m/%Y %H:%M') %></td>
      <td><%= @num_passengers %></td>
    </tr>

    <% end %>
    <tr>
    <td><%= f.submit 'Book' %></td>
  </tr>
<% end %>
</table>
<% else %>
  <p>There is no flight match</p>
<% end %>

app/views/flights/index.html.erb
<h1>Flights:</h1>
<table >
<%= form_with scope: :flight, url: flights_path, method: :get, local: true,data:{turbo: false} do |f| %>
    <tr>
      <th><%= f.label :start_airport, 'From', class: 'label' %></th>
      <th><%= f.label :finish_airport, 'To', class: 'label' %></th>
      <th><%= f.label :start_datetime, 'Date', class: 'label' %></th>
      <th><%= f.label :num_passengers, 'Tickets', class: 'label' %></th>
    </tr>
    <tr>

    <td>
      <div >
        <%= f.select :departure_airport, options_for_select(@airports) %>
      </div>
    </td>
    <td>
      <div >
        <%= f.select :arrival_airport, options_for_select(@airports), include_blank: true %>
      </div>
    </td>
    <td>
      <div >
        <%= f.select :start_datetime, options_for_select(@start_datetime), include_blank: true %>
      </div>
    </td>
    <td>
    <div >
      <%= f.select :num_passengers, options_for_select([1,2,3,4]) %>
    </div>
  </td>
   
  </tr>
  <tr>
    <td>
      <%= f.submit 'Search' %>
    </td>
  </tr>
<%end%>
</table>
<% if @results %>
<%= render "results" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   
  </head>

  <body>
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
  <%= link_to "Home",root_path %>
    <%= yield %>
  </body>
</html>